#!/usr/bin/env python3
"""
Convert data/resolved_sale_data.json into src/data/saleData.ts — a typed TS
literal the app imports directly, mirroring how clearanceData.ts used to be
hand-written, but generated instead.

Usage: python3 scripts/generate_app_data.py
Output: src/data/saleData.ts
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DATA_DIR = ROOT / "data"
OUTPUT_TS = ROOT / "src" / "data" / "saleData.ts"

HEADER = """// Generated by scripts/generate_app_data.py — do not hand-edit.
// Regenerate via: python3 scripts/extract_pdf_data.py && python3 scripts/extract_predictions_data.py && python3 scripts/resolve_sale_data.py && python3 scripts/generate_app_data.py

export type PrintSource = 'predictions-product' | 'pdf-only-swatch' | 'pdf-only-missing';
export type DaySource = 'pdf' | 'default-carryover' | 'default-conflict';
// 'pdf-confirmed': PDF starting price matches this product's live smallest-size
// price exactly, so its real per-size price ladder is trusted as-is.
// 'pdf-starting-only': PDF price could not be confirmed against a live product
// (or didn't match one) — only the smallest size's price is known; larger
// sizes may cost more. 'predictions': no PDF coverage, live price range used.
// 'manual-override': no PDF/predictions sale-price evidence at all — a flat
// historical sale price was hand-entered in aliases.json's manual_price_overrides.
export type PriceSource = 'pdf-confirmed' | 'pdf-starting-only' | 'predictions' | 'manual-override';

export interface ProductVariantInfo {
  size: string;
  sku?: string;
  price?: number;
}

export interface ProductMatch {
  productId: number;
  productTitle: string;
  productUrl: string;
  localImage: string;
  variants: ProductVariantInfo[];
  isFirstTimeOnClearance: boolean;
}

export interface PriceRange {
  min: number;
  max: number;
}

export interface EnrichedPrint {
  name: string;
  day: 'friday' | 'sunday';
  daySource: DaySource;
  source: PrintSource;
  imageUrl?: string | null;
  // A plain color swatch (remote printDatabase URL or local public/swatches/
  // file), resolved regardless of `source` — used by the grouped view's
  // small tiles, which show swatches even for real-photo-backed prints.
  swatchImageUrl?: string | null;
  price: PriceRange | null;
  priceSource: PriceSource;
  // True when the pipeline found zero sale-price evidence anywhere (no PDF
  // coverage, and the predictions scrape found no compare_at_price/discount
  // either) — `price` above is just Kyte's regular retail price.
  noSalePriceFound: boolean;
  productMatch?: ProductMatch | null;
}

export interface SaleEntry {
  id: string;
  name: string;
  section: string;
  fridayPrints: EnrichedPrint[];
  sundayPrints: EnrichedPrint[];
}

"""


def main():
    resolved = json.loads((DATA_DIR / "resolved_sale_data.json").read_text())

    sale_entries = []
    for entry in resolved:
        friday_prints = [p for p in entry["prints"] if p["day"] == "friday"]
        sunday_prints = [p for p in entry["prints"] if p["day"] == "sunday"]
        sale_entries.append({
            "id": entry["id"],
            "name": entry["name"],
            "section": entry["section"],
            "fridayPrints": friday_prints,
            "sundayPrints": sunday_prints,
        })

    body = json.dumps(sale_entries, indent=2)
    ts_content = HEADER + f"export const saleEntries: SaleEntry[] = {body};\n"
    OUTPUT_TS.write_text(ts_content)

    total_friday = sum(len(e["fridayPrints"]) for e in sale_entries)
    total_sunday = sum(len(e["sundayPrints"]) for e in sale_entries)
    print(f"Wrote {OUTPUT_TS} ({len(sale_entries)} entries, {total_friday} Friday prints, {total_sunday} Sunday prints)")


if __name__ == "__main__":
    main()
